### PR TITLE
Genre component

### PR DESCRIPTION
**Pull request by intertemp**

### CODE REVIEW

**Review by RealBirdMan91 — COMMENTED** [review]
So Mora finished the routing. Pull the main and merge it in your repository. So you can Place your component on the Home Page.

Also make your button a cursor.

After that write a story which reflects your component state for the btn

**Review by ReallyBoard123 — CHANGES_REQUESTED** [review]
missingInfo

I cannot find the information regarding who is currently working on this. So please assign yourself this issue. Also, which issue does this component relate to. Also add that information

**Comment by intertemp** [comment]
Everything is done!

**Comment by RealBirdMan91** [comment]
Please also assign to your Pull Request you can do that on the right. Its the Assignees tab

**Pull request closed without merging**
